spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
